'use client';

import { useState } from 'react';
import styles from './RemediationView.module.css';

interface CodeExample {
    vulnerable: string;
    secure: string;
    language: string;
    explanation: string;
}

interface RemediationViewProps {
    vulnerability: {
        title: string;
        severity: string;
        category: string;
    };
}

export default function RemediationView({ vulnerability }: RemediationViewProps) {
    const [copied, setCopied] = useState(false);

    // Mock remediation code - in production, this would be generated by AI
    const remediation: CodeExample = {
        language: 'javascript',
        vulnerable: `// ❌ VULNERABLE CODE
const getUserData = (userId) => {
    const query = "SELECT * FROM users WHERE id = '" + userId + "'";
    return db.query(query);
};

app.get('/user/:id', (req, res) => {
    const data = getUserData(req.params.id);
    res.json(data);
});`,
        secure: `// ✅ SECURE CODE
const getUserData = (userId) => {
    // Use parameterized queries to prevent SQL injection
    const query = "SELECT * FROM users WHERE id = $1";
    return db.query(query, [userId]);
};

app.get('/user/:id', (req, res) => {
    // Validate and sanitize input
    const userId = parseInt(req.params.id, 10);
    if (isNaN(userId)) {
        return res.status(400).json({ error: 'Invalid user ID' });
    }
    
    const data = getUserData(userId);
    res.json(data);
});`,
        explanation: `**Key Changes:**
1. **Parameterized Queries**: Using $1 placeholder prevents SQL injection
2. **Input Validation**: Parse and validate user ID before use
3. **Type Checking**: Ensure ID is a number, not arbitrary string
4. **Error Handling**: Return 400 for invalid input

**Why This Works:**
Parameterized queries send SQL code and data separately, preventing attackers from injecting malicious SQL commands through user input.`,
    };

    const copySecureCode = () => {
        navigator.clipboard.writeText(remediation.secure);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const downloadPatch = () => {
        const patch = `--- Vulnerable Code
+++ Secure Code
@@ -1,7 +1,14 @@
${remediation.vulnerable.split('\n').map(line => `- ${line}`).join('\n')}
${remediation.secure.split('\n').map(line => `+ ${line}`).join('\n')}
`;
        const blob = new Blob([patch], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.create Element('a');
        a.href = url;
        a.download = `${vulnerability.title.replace(/\s+/g, '_')}_remediation.patch`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className={styles.container}>
            <div className={styles.header}>
                <div>
                    <h2>🔧 Remediation Guide</h2>
                    <p className={styles.subtitle}>AI-generated secure code fix for {vulnerability.title}</p>
                </div>
                <div className={styles.actions}>
                    <button className={styles.btn} onClick={copySecureCode}>
                        {copied ? '✓ Copied!' : '📋 Copy Secure Code'}
                    </button>
                    <button className={styles.btn} onClick={downloadPatch}>
                        💾 Download Patch
                    </button>
                </div>
            </div>

            <div className={styles.diffContainer}>
                <div className={styles.codeBlock}>
                    <div className={styles.codeHeader}>
                        <span className={styles.fileLabel}>❌ Vulnerable Code</span>
                        <span className={styles.langBadge}>{remediation.language}</span>
                    </div>
                    <pre className={`${styles.code} ${styles.vulnerable}`}>
                        <code>{remediation.vulnerable}</code>
                    </pre>
                </div>

                <div className={styles.arrow}>→</div>

                <div className={styles.codeBlock}>
                    <div className={styles.codeHeader}>
                        <span className={styles.fileLabel}>✅ Secure Code</span>
                        <span className={styles.langBadge}>{remediation.language}</span>
                    </div>
                    <pre className={`${styles.code} ${styles.secure}`}>
                        <code>{remediation.secure}</code>
                    </pre>
                </div>
            </div>

            <div className={styles.explanation}>
                <h3>💡 Explanation</h3>
                <div className={styles.explanationContent} dangerouslySetInnerHTML={{ __html: remediation.explanation.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br/>') }} />
            </div>

            <div className={styles.footer}>
                <div className={styles.references}>
                    <h4>📚 References:</h4>
                    <ul>
                        <li><a href="https://owasp.org/www-community/attacks/SQL_Injection" target="_blank" rel="noopener noreferrer">OWASP: SQL Injection</a></li>
                        <li><a href="https://cwe.mitre.org/data/definitions/89.html" target="_blank" rel="noopener noreferrer">CWE-89: SQL Injection</a></li>
                        <li><a href="https://cheatsheetseries.owasp.org/cheatsheets/Query_Parameterization_Cheat_Sheet.html" target="_blank" rel="noopener noreferrer">OWASP: Query Parameterization</a></li>
                    </ul>
                </div>
            </div>
        </div>
    );
}
